version: "3.8"

services:
  maintainerr-overlay-helperr:
    image: gsariev/maintainerr-overlay-helperr:develop
    container_name: maintainerr-overlay-helperr
    ports:
      - "3000:3000"
    volumes:
      - /path/to/data:/data           # config.json + state + saved posters
      - /path/to/fonts:/fonts         # custom .ttf fonts (optional)
    environment:
      - PLEX_URL=http://your-plex-host:32400
      - PLEX_TOKEN=your-plex-token
      - MAINTAINERR_URL=http://your-maintainerr-host:6246

    restart: unless-stopped
